### ISSUE TITLE
Interpretation of denoised counts

### ISSUE THREAD

**Issue by mdmanurung** [CaibinSh/scAR-reproducibility#2]
Hi Caibin,

Could you briefly explain the interpretation of denoised counts given by scAR? I noticed that it returns floats, not counts. How should I then normalise the data? Just log2(x+1) after scaling by library size?

Regards,
Mikhael

**Comment by CaibinSh** [comment]
Hi Mikhael,

scAR uses imputation as several other methods, including DCA, scVI, and totalVI. The denoised counts are expected values based on the probability scAR returned, so it is float, rather than an integer.

For example, for a cell A with 4 genes, the real counts are [1, 2, 5, 1], but observed counts (10x output) may be [0,1,3,1] due to many factors, such as capture rate and random noise. If we sequence the same cells infinite times (of course, we cannot), we may get the real counts. What scAR is doing is to estimate the real counts based on the observed counts [0,1,3,1] and features of similar cells.

Best, Caibin

**Comment by mdmanurung** [comment]
I see. I should to try this myself, but have you tried using scAR output as input for TotalVI? If I recall correctly, the latter requires raw counts.

**Comment by CaibinSh** [comment]
I haven't tried using totalVI after scAR, but it should be fine to do this. scAR-denoised counts represent the expected native counts, the distribution of which is quite similar to raw counts (it contains more zeros than raw counts). It is worthy a try given the versatile functions that totalVI has.
